# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgparasetting_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(427, 152)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label.setObjectName("label")
        self.lineEdit_OutDir = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_OutDir.setEnabled(False)
        self.lineEdit_OutDir.setGeometry(QtCore.QRect(75, 15, 290, 20))
        self.lineEdit_OutDir.setObjectName("lineEdit_OutDir")
        self.pushButton_OutDir = QtWidgets.QPushButton(Dialog)
        self.pushButton_OutDir.setGeometry(QtCore.QRect(375, 15, 30, 23))
        self.pushButton_OutDir.setObjectName("pushButton_OutDir")
        self.pushButton_Ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_Ok.setGeometry(QtCore.QRect(100, 90, 76, 41))
        self.pushButton_Ok.setObjectName("pushButton_Ok")
        self.pushButton_Cancle = QtWidgets.QPushButton(Dialog)
        self.pushButton_Cancle.setGeometry(QtCore.QRect(250, 90, 76, 41))
        self.pushButton_Cancle.setObjectName("pushButton_Cancle")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "参数设置"))
        self.label.setText(_translate("Dialog", "输出目录"))
        self.pushButton_OutDir.setText(_translate("Dialog", "..."))
        self.pushButton_Ok.setText(_translate("Dialog", "确定"))
        self.pushButton_Cancle.setText(_translate("Dialog", "取消"))
import res_rc
