# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 644)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_OpenDir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OpenDir.setGeometry(QtCore.QRect(640, 40, 111, 41))
        self.pushButton_OpenDir.setObjectName("pushButton_OpenDir")
        self.pushButton_Handle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Handle.setGeometry(QtCore.QRect(640, 100, 111, 41))
        self.pushButton_Handle.setObjectName("pushButton_Handle")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 621, 581))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionParaSetting = QtWidgets.QAction(MainWindow)
        self.actionParaSetting.setObjectName("actionParaSetting")
        self.menu.addAction(self.actionParaSetting)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "目标检测数据增强"))
        self.pushButton_OpenDir.setText(_translate("MainWindow", "打开目录"))
        self.pushButton_Handle.setText(_translate("MainWindow", "处理数据"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.actionParaSetting.setText(_translate("MainWindow", "参数设置"))
